package com.reqman.pojo;

// Generated 13 Aug, 2017 10:25:05 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Audittrail generated by hbm2java
 */
@Entity
@Table(name = "audittrail")
public class Audittrail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2249984171100876658L;
	private int id;
	private String userid;
	private String requestheader;
	private String responseheader;
	private Boolean status;
	private Date datecreated;
	private String username;

	public Audittrail() {
	}

	public Audittrail(int id) {
		this.id = id;
	}

	public Audittrail(int id, String userid, String requestheader,
			String responseheader, Boolean status, Date datecreated,
			String username) {
		this.id = id;
		this.userid = userid;
		this.requestheader = requestheader;
		this.responseheader = responseheader;
		this.status = status;
		this.datecreated = datecreated;
		this.username = username;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "userid", length = 100)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "requestheader")
	public String getRequestheader() {
		return this.requestheader;
	}

	public void setRequestheader(String requestheader) {
		this.requestheader = requestheader;
	}

	@Column(name = "responseheader")
	public String getResponseheader() {
		return this.responseheader;
	}

	public void setResponseheader(String responseheader) {
		this.responseheader = responseheader;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecreated", length = 29)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@Column(name = "username", length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
