package com.reqman.pojo;

// Generated 13 Aug, 2017 10:25:05 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Requestworkflow generated by hbm2java
 */
@Entity
@Table(name = "requestworkflow")
public class Requestworkflow implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2904580197239592798L;
	private int id;
	private Request request;
	private Userfriendlist userfriendlist;
	private Integer requestid;
	private Integer friendid;
	private Float completionpercentage;
	private String requestby;
	private Integer requeststatus;
	private Date acceptdate;
	private Date updatedate;
	private Integer revisionnumber;
	private String approvedby;
	private Date approveddate;
	private Date datecreated;
	private String createdby;
	private Date datemodified;
	private String modifiedby;

	public Requestworkflow() {
	}

	public Requestworkflow(Request request, Userfriendlist userfriendlist) {
		this.request = request;
		this.userfriendlist = userfriendlist;
	}

	public Requestworkflow(Request request, Userfriendlist userfriendlist,
			Integer requestid, Integer friendid, Float completionpercentage,
			String requestby, Integer requeststatus, Date acceptdate,
			Date updatedate, Integer revisionnumber, String approvedby,
			Date approveddate, Date datecreated, String createdby,
			Date datemodified, String modifiedby) {
		this.request = request;
		this.userfriendlist = userfriendlist;
		this.requestid = requestid;
		this.friendid = friendid;
		this.completionpercentage = completionpercentage;
		this.requestby = requestby;
		this.requeststatus = requeststatus;
		this.acceptdate = acceptdate;
		this.updatedate = updatedate;
		this.revisionnumber = revisionnumber;
		this.approvedby = approvedby;
		this.approveddate = approveddate;
		this.datecreated = datecreated;
		this.createdby = createdby;
		this.datemodified = datemodified;
		this.modifiedby = modifiedby;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "request"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Request getRequest() {
		return this.request;
	}

	public void setRequest(Request request) {
		this.request = request;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Userfriendlist getUserfriendlist() {
		return this.userfriendlist;
	}

	public void setUserfriendlist(Userfriendlist userfriendlist) {
		this.userfriendlist = userfriendlist;
	}

	@Column(name = "requestid")
	public Integer getRequestid() {
		return this.requestid;
	}

	public void setRequestid(Integer requestid) {
		this.requestid = requestid;
	}

	@Column(name = "friendid")
	public Integer getFriendid() {
		return this.friendid;
	}

	public void setFriendid(Integer friendid) {
		this.friendid = friendid;
	}

	@Column(name = "completionpercentage", precision = 8, scale = 8)
	public Float getCompletionpercentage() {
		return this.completionpercentage;
	}

	public void setCompletionpercentage(Float completionpercentage) {
		this.completionpercentage = completionpercentage;
	}

	@Column(name = "requestby", length = 50)
	public String getRequestby() {
		return this.requestby;
	}

	public void setRequestby(String requestby) {
		this.requestby = requestby;
	}

	@Column(name = "requeststatus")
	public Integer getRequeststatus() {
		return this.requeststatus;
	}

	public void setRequeststatus(Integer requeststatus) {
		this.requeststatus = requeststatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "acceptdate", length = 29)
	public Date getAcceptdate() {
		return this.acceptdate;
	}

	public void setAcceptdate(Date acceptdate) {
		this.acceptdate = acceptdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedate", length = 29)
	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	@Column(name = "revisionnumber")
	public Integer getRevisionnumber() {
		return this.revisionnumber;
	}

	public void setRevisionnumber(Integer revisionnumber) {
		this.revisionnumber = revisionnumber;
	}

	@Column(name = "approvedby", length = 50)
	public String getApprovedby() {
		return this.approvedby;
	}

	public void setApprovedby(String approvedby) {
		this.approvedby = approvedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approveddate", length = 29)
	public Date getApproveddate() {
		return this.approveddate;
	}

	public void setApproveddate(Date approveddate) {
		this.approveddate = approveddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecreated", length = 29)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@Column(name = "createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datemodified", length = 29)
	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	@Column(name = "modifiedby", length = 50)
	public String getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(String modifiedby) {
		this.modifiedby = modifiedby;
	}

}
