package com.reqman.pojo;

// Generated 13 Aug, 2017 10:25:05 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rolemenus generated by hbm2java
 */
@Entity
@Table(name = "rolemenus")
public class Rolemenus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3136997859372747316L;
	private RolemenusId id;
	private Menu menu;
	private Roles roles;

	public Rolemenus() {
	}

	public Rolemenus(RolemenusId id) {
		this.id = id;
	}

	public Rolemenus(RolemenusId id, Menu menu, Roles roles) {
		this.id = id;
		this.menu = menu;
		this.roles = roles;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "roleid", column = @Column(name = "roleid")),
			@AttributeOverride(name = "menuid", column = @Column(name = "menuid")) })
	public RolemenusId getId() {
		return this.id;
	}

	public void setId(RolemenusId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menuid", insertable = false, updatable = false)
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleid", insertable = false, updatable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
