package com.reqman.pojo;

// Generated 13 Aug, 2017 10:25:05 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolemenusId generated by hbm2java
 */
@Embeddable
public class RolemenusId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1493398613418587111L;
	private Integer roleid;
	private Integer menuid;

	public RolemenusId() {
	}

	public RolemenusId(Integer roleid, Integer menuid) {
		this.roleid = roleid;
		this.menuid = menuid;
	}

	@Column(name = "roleid")
	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	@Column(name = "menuid")
	public Integer getMenuid() {
		return this.menuid;
	}

	public void setMenuid(Integer menuid) {
		this.menuid = menuid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolemenusId))
			return false;
		RolemenusId castOther = (RolemenusId) other;

		return ((this.getRoleid() == castOther.getRoleid()) || (this
				.getRoleid() != null && castOther.getRoleid() != null && this
				.getRoleid().equals(castOther.getRoleid())))
				&& ((this.getMenuid() == castOther.getMenuid()) || (this
						.getMenuid() != null && castOther.getMenuid() != null && this
						.getMenuid().equals(castOther.getMenuid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRoleid() == null ? 0 : this.getRoleid().hashCode());
		result = 37 * result
				+ (getMenuid() == null ? 0 : this.getMenuid().hashCode());
		return result;
	}

}
