package com.reqman.pojo;

// Generated 13 Aug, 2017 10:25:05 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userroles generated by hbm2java
 */
@Entity
@Table(name = "userroles")
public class Userroles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 465617079133923104L;
	private UserrolesId id;
	private Roles roles;
	private Users users;

	public Userroles() {
	}

	public Userroles(UserrolesId id) {
		this.id = id;
	}

	public Userroles(UserrolesId id, Roles roles, Users users) {
		this.id = id;
		this.roles = roles;
		this.users = users;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "roleid", column = @Column(name = "roleid")),
			@AttributeOverride(name = "userid", column = @Column(name = "userid")) })
	public UserrolesId getId() {
		return this.id;
	}

	public void setId(UserrolesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleid", insertable = false, updatable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
