package com.reqman.pojo;

// Generated 13 Aug, 2017 10:25:05 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usertype generated by hbm2java
 */
@Entity
@Table(name = "usertype")
public class Usertype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8018919747883242757L;
	private int id;
	private String name;
	private Boolean status;
	private Date datecreated;
	private String createdby;
	private Set<Userusertype> userusertypes = new HashSet<Userusertype>(0);

	public Usertype() {
	}

	public Usertype(int id) {
		this.id = id;
	}

	public Usertype(int id, String name, Boolean status, Date datecreated,
			String createdby, Set<Userusertype> userusertypes) {
		this.id = id;
		this.name = name;
		this.status = status;
		this.datecreated = datecreated;
		this.createdby = createdby;
		this.userusertypes = userusertypes;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecreated", length = 29)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@Column(name = "createdby", length = 50)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usertype")
	public Set<Userusertype> getUserusertypes() {
		return this.userusertypes;
	}

	public void setUserusertypes(Set<Userusertype> userusertypes) {
		this.userusertypes = userusertypes;
	}

}
