package com.reqman.pojo;

// Generated 13 Aug, 2017 10:25:05 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userusertype generated by hbm2java
 */
@Entity
@Table(name = "userusertype")
public class Userusertype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7439055638445746607L;
	private UserusertypeId id;
	private Users users;
	private Usertype usertype;

	public Userusertype() {
	}

	public Userusertype(UserusertypeId id) {
		this.id = id;
	}

	public Userusertype(UserusertypeId id, Users users, Usertype usertype) {
		this.id = id;
		this.users = users;
		this.usertype = usertype;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "usertypeid", column = @Column(name = "usertypeid")),
			@AttributeOverride(name = "userid", column = @Column(name = "userid")) })
	public UserusertypeId getId() {
		return this.id;
	}

	public void setId(UserusertypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usertypeid", insertable = false, updatable = false)
	public Usertype getUsertype() {
		return this.usertype;
	}

	public void setUsertype(Usertype usertype) {
		this.usertype = usertype;
	}

}
